export const brand = {
  orange: '#E65100',
  orangeLight: '#FF8A50',
  orangeMuted: '#F4845F',
  cream: '#FFF8F0',
  warmGray: '#FAF5F0',
  charcoal: '#1C1410',
  darkSurface: '#261C14',
  darkCard: '#332218',
};

export default {
  light: {
    text: '#2D1B0E',
    textSecondary: '#78604B',
    background: brand.warmGray,
    card: '#FFFFFF',
    tint: brand.orange,
    border: '#F0E4D8',
    muted: '#9C8572',
    accent: brand.orange,
    accentLight: brand.orangeLight,
    danger: '#D84315',
    success: '#2E7D32',
    chatBubbleUser: brand.orange,
    chatBubbleBot: '#FFF3E0',
    chatBubbleBotText: '#3E2723',
  },
  dark: {
    text: '#F5EDE6',
    textSecondary: '#BFA48E',
    background: brand.charcoal,
    card: brand.darkCard,
    tint: brand.orangeLight,
    border: '#3D2C1E',
    muted: '#8C7560',
    accent: brand.orangeLight,
    accentLight: brand.orange,
    danger: '#FF6E40',
    success: '#66BB6A',
    chatBubbleUser: brand.orange,
    chatBubbleBot: brand.darkSurface,
    chatBubbleBotText: '#F5EDE6',
  },
};
